/** Warm Precision design tokens */
export const theme = {
  name: "Warm Precision",
  colors: {
    light: {
      background: "#fbf8ff",
      surface: "#ffffff",
      surfaceContainerLow: "#f4f2fd",
      surfaceContainer: "#eeedf7",
      surfaceContainerHigh: "#e8e7f1",
      card: "#ffffff",
      border: "#c7c4d8",
      foreground: "#1a1b22",
      muted: "#464555",
      mutedForeground: "#777587",
      primary: "#3525cd",
      primaryForeground: "#ffffff",
      primaryContainer: "#4f46e5",
      surfaceTint: "#4d44e3",
      inversePrimary: "#c3c0ff",
      secondary: "#805533",
      secondaryContainer: "#fdc39a",
      success: "#1a7f4b",
      warning: "#b45309",
      danger: "#ba1a1a",
      hover: "#f4f2fd",
      ring: "#4d44e3",
    },
    dark: {
      background: "#1a1820",
      surface: "#2f3038",
      surfaceContainerLow: "#2a2832",
      surfaceContainer: "#2f2d38",
      surfaceContainerHigh: "#36343f",
      card: "#2f3038",
      border: "#4a4756",
      foreground: "#f1effa",
      muted: "#b8b4c8",
      mutedForeground: "#8a8699",
      primary: "#c3c0ff",
      primaryForeground: "#0f0069",
      primaryContainer: "#4f46e5",
      surfaceTint: "#4d44e3",
      inversePrimary: "#3525cd",
      secondary: "#fdc39a",
      secondaryContainer: "#653d1e",
      success: "#4ade80",
      warning: "#fbbf24",
      danger: "#f87171",
      hover: "#36343f",
      ring: "#c3c0ff",
    },
  },
  typography: {
    displayLg: { fontSize: "48px", mobileFontSize: "32px", fontWeight: 700, lineHeight: 1.1 },
    headlineMd: { fontSize: "24px", fontWeight: 600, lineHeight: 1.3 },
    bodyLg: { fontSize: "18px", fontWeight: 400, lineHeight: 1.6 },
    bodyMd: { fontSize: "16px", fontWeight: 400, lineHeight: 1.5 },
    labelSm: { fontSize: "13px", fontWeight: 600, lineHeight: 1, letterSpacing: "0.05em" },
  },
  radius: {
    card: "0.75rem",
    button: "0.75rem",
    input: "0.75rem",
    badge: "0.5rem",
    sm: "0.25rem",
    md: "0.75rem",
    lg: "1rem",
    xl: "1.5rem",
  },
  spacing: {
    unit: 4,
    containerMax: 100,
    gutter: 24,
    marginDesktop: 64,
    marginMobile: 20,
    stackSm: 12,
    stackMd: 24,
    stackLg: 48,
  },
  layout: {
    headerHeight: "4.375rem",
    maxWidth: "100%",
  },
  motion: {
    fadeUpDuration: 0.3,
    fadeUpEase: [0.2, 0.8, 0.2, 1] as const,
    themeTransition: "200ms ease",
    heroFloatDuration: 5,
  },
} as const

export type Theme = typeof theme
